### ISSUE TITLE
Allow "after" (and other event timings) to have a list of event ids

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/picaro#31]
Something like:

``` yaml
attack:
  after:
    - takeAHit
    - laughHeartily
    - hitBack
```

Where those are three different custom events under the `events` section of the game. This would let you reuse modular events and also just structure the script in a more skimmable format.
