### ISSUE TITLE
Process action guard(s) before moving to a new room

### ISSUE THREAD

**Issue by ckolderup** [ckolderup/picaro#33]
It would look like this:

``` yaml
rooms: 
- name: Your Apartment
  paths:
    E:
    - room: Outside
      actionGuard: foundWallet
```

If the "foundWallet" action guard fails, you won't move to the room to the east.

One thing that we might want to consider is that for action guards like this, there might be some need to "destroy" them, which I'm afraid is complicated to implement but basically means that if they pass once, they should never test again.
